f=open("SQUARE.INP")
f1=open("SQUARE.OUT","w")
n=int(f.readline())
xmax=0
ymax=0
xmin=10**12
ymin=10**12
for i in f:
    x,y=i.split()
    x,y=int(x),int(y)
    xmax=max(xmax,x)
    ymax=max(ymax,y)
    xmin=min(xmin,x)                                                                                                                                                      
    ymin=min(ymin,y)
d=xmax-xmin
r=ymax-ymin
c=max(d,r)
f1.write(str(c*c))
f.close()
f1.close()
